
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'ActiviteeDetail': typeof import("../layers/reservation/components/ActiviteeDetail.vue")['default']
    'ActiviteeDetailItem': typeof import("../layers/reservation/components/ActiviteeDetailItem.vue")['default']
    'ActivityCard': typeof import("../layers/reservation/components/ActivityCard.vue")['default']
    'DogCard': typeof import("../layers/reservation/components/DogCard.vue")['default']
    'DogCardList': typeof import("../layers/reservation/components/DogCardList.vue")['default']
    'HelloWorld': typeof import("../layers/reservation/components/HelloWorld.vue")['default']
    'IsApproved': typeof import("../layers/reservation/components/IsApproved.vue")['default']
    'LoginButton': typeof import("../layers/reservation/components/LoginButton.vue")['default']
    'LoginControls': typeof import("../layers/reservation/components/LoginControls.vue")['default']
    'MomentAgo': typeof import("../layers/reservation/components/MomentAgo.vue")['default']
    'MyFooter': typeof import("../layers/reservation/components/MyFooter.vue")['default']
    'TheWelcome': typeof import("../layers/reservation/components/TheWelcome.vue")['default']
    'WelcomeItem': typeof import("../layers/reservation/components/WelcomeItem.vue")['default']
    'AnimalCard': typeof import("../layers/reservation/components/animal/AnimalCard.vue")['default']
    'AnimalForm': typeof import("../layers/reservation/components/animal/AnimalForm.vue")['default']
    'AnimalList': typeof import("../layers/reservation/components/animal/AnimalList.vue")['default']
    'AnimalSelect': typeof import("../layers/reservation/components/animal/AnimalSelect.vue")['default']
    'ButtonsCardAddButton': typeof import("../layers/reservation/components/buttons/CardAddButton.vue")['default']
    'ButtonsFacebookButton': typeof import("../layers/reservation/components/buttons/FacebookButton.vue")['default']
    'CalendarAdminCalendar': typeof import("../layers/reservation/components/calendar/AdminCalendar.vue")['default']
    'CalendarAvailabilitiesCalendar': typeof import("../layers/reservation/components/calendar/AvailabilitiesCalendar.vue")['default']
    'CalendarClientCalendar': typeof import("../layers/reservation/components/calendar/ClientCalendar.vue")['default']
    'ColorpickerColorCircle': typeof import("../layers/reservation/components/colorpicker/ColorCircle.vue")['default']
    'ColorpickerColorPicker': typeof import("../layers/reservation/components/colorpicker/ColorPicker.vue")['default']
    'EventUtils': typeof import("../layers/reservation/components/event-utils")['default']
    'IconsIconCommunity': typeof import("../layers/reservation/components/icons/IconCommunity.vue")['default']
    'IconsIconDocumentation': typeof import("../layers/reservation/components/icons/IconDocumentation.vue")['default']
    'IconsIconEcosystem': typeof import("../layers/reservation/components/icons/IconEcosystem.vue")['default']
    'IconsIconHamburger': typeof import("../layers/reservation/components/icons/IconHamburger.vue")['default']
    'IconsIconSupport': typeof import("../layers/reservation/components/icons/IconSupport.vue")['default']
    'IconsIconTooling': typeof import("../layers/reservation/components/icons/IconTooling.vue")['default']
    'IconsIconUser': typeof import("../layers/reservation/components/icons/IconUser.vue")['default']
    'InputsImageFileDisplay': typeof import("../layers/reservation/components/inputs/ImageFileDisplay.vue")['default']
    'InputsImageFileInput': typeof import("../layers/reservation/components/inputs/ImageFileInput.vue")['default']
    'ModalsModal': typeof import("../layers/reservation/components/modals/Modal.vue")['default']
    'ModalsReserveModal': typeof import("../layers/reservation/components/modals/ReserveModal.vue")['default']
    'NavigationHeader': typeof import("../layers/reservation/components/navigation/NavigationHeader.vue")['default']
    'NavigationSubMenu': typeof import("../layers/reservation/components/navigation/SubMenu.vue")['default']
    'ReservationCard': typeof import("../layers/reservation/components/reservation/ReservationCard.vue")['default']
    'ReservationForm': typeof import("../layers/reservation/components/reservation/ReservationForm.vue")['default']
    'ReservationList': typeof import("../layers/reservation/components/reservation/ReservationList.vue")['default']
    'TeamCard': typeof import("../layers/reservation/components/team/TeamCard.vue")['default']
    'TeamCardList': typeof import("../layers/reservation/components/team/TeamCardList.vue")['default']
    'TeamCardPreview': typeof import("../layers/reservation/components/team/TeamCardPreview.vue")['default']
    'TeamCards': typeof import("../layers/reservation/components/team/TeamCards.vue")['default']
    'TeamProfile': typeof import("../layers/reservation/components/team/TeamProfile.vue")['default']
    'TeamProfileEdit': typeof import("../layers/reservation/components/team/TeamProfileEdit.vue")['default']
    'UserAnimals': typeof import("../layers/reservation/components/user/UserAnimals.vue")['default']
    'UserDetail': typeof import("../layers/reservation/components/user/UserDetail.vue")['default']
    'UserForm': typeof import("../layers/reservation/components/user/UserForm.vue")['default']
    'UAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'UAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'UAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'UAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'UBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'UButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'UButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'UCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'UChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'UDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'UIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'UKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'ULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'UMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'UMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'UProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'UCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'UForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'UFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'UInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'UInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'URadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'URadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'URange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'USelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'USelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'UTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'UToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'UTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'UCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'UContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'UDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'USkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'UBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'UCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'UCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'UHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'UPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'UTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'UVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'UContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'UModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'UModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'UNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'UNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'UPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'USlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'USlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'UTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'UModals': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'USlideovers': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyActiviteeDetail': typeof import("../layers/reservation/components/ActiviteeDetail.vue")['default']
    'LazyActiviteeDetailItem': typeof import("../layers/reservation/components/ActiviteeDetailItem.vue")['default']
    'LazyActivityCard': typeof import("../layers/reservation/components/ActivityCard.vue")['default']
    'LazyDogCard': typeof import("../layers/reservation/components/DogCard.vue")['default']
    'LazyDogCardList': typeof import("../layers/reservation/components/DogCardList.vue")['default']
    'LazyHelloWorld': typeof import("../layers/reservation/components/HelloWorld.vue")['default']
    'LazyIsApproved': typeof import("../layers/reservation/components/IsApproved.vue")['default']
    'LazyLoginButton': typeof import("../layers/reservation/components/LoginButton.vue")['default']
    'LazyLoginControls': typeof import("../layers/reservation/components/LoginControls.vue")['default']
    'LazyMomentAgo': typeof import("../layers/reservation/components/MomentAgo.vue")['default']
    'LazyMyFooter': typeof import("../layers/reservation/components/MyFooter.vue")['default']
    'LazyTheWelcome': typeof import("../layers/reservation/components/TheWelcome.vue")['default']
    'LazyWelcomeItem': typeof import("../layers/reservation/components/WelcomeItem.vue")['default']
    'LazyAnimalCard': typeof import("../layers/reservation/components/animal/AnimalCard.vue")['default']
    'LazyAnimalForm': typeof import("../layers/reservation/components/animal/AnimalForm.vue")['default']
    'LazyAnimalList': typeof import("../layers/reservation/components/animal/AnimalList.vue")['default']
    'LazyAnimalSelect': typeof import("../layers/reservation/components/animal/AnimalSelect.vue")['default']
    'LazyButtonsCardAddButton': typeof import("../layers/reservation/components/buttons/CardAddButton.vue")['default']
    'LazyButtonsFacebookButton': typeof import("../layers/reservation/components/buttons/FacebookButton.vue")['default']
    'LazyCalendarAdminCalendar': typeof import("../layers/reservation/components/calendar/AdminCalendar.vue")['default']
    'LazyCalendarAvailabilitiesCalendar': typeof import("../layers/reservation/components/calendar/AvailabilitiesCalendar.vue")['default']
    'LazyCalendarClientCalendar': typeof import("../layers/reservation/components/calendar/ClientCalendar.vue")['default']
    'LazyColorpickerColorCircle': typeof import("../layers/reservation/components/colorpicker/ColorCircle.vue")['default']
    'LazyColorpickerColorPicker': typeof import("../layers/reservation/components/colorpicker/ColorPicker.vue")['default']
    'LazyEventUtils': typeof import("../layers/reservation/components/event-utils")['default']
    'LazyIconsIconCommunity': typeof import("../layers/reservation/components/icons/IconCommunity.vue")['default']
    'LazyIconsIconDocumentation': typeof import("../layers/reservation/components/icons/IconDocumentation.vue")['default']
    'LazyIconsIconEcosystem': typeof import("../layers/reservation/components/icons/IconEcosystem.vue")['default']
    'LazyIconsIconHamburger': typeof import("../layers/reservation/components/icons/IconHamburger.vue")['default']
    'LazyIconsIconSupport': typeof import("../layers/reservation/components/icons/IconSupport.vue")['default']
    'LazyIconsIconTooling': typeof import("../layers/reservation/components/icons/IconTooling.vue")['default']
    'LazyIconsIconUser': typeof import("../layers/reservation/components/icons/IconUser.vue")['default']
    'LazyInputsImageFileDisplay': typeof import("../layers/reservation/components/inputs/ImageFileDisplay.vue")['default']
    'LazyInputsImageFileInput': typeof import("../layers/reservation/components/inputs/ImageFileInput.vue")['default']
    'LazyModalsModal': typeof import("../layers/reservation/components/modals/Modal.vue")['default']
    'LazyModalsReserveModal': typeof import("../layers/reservation/components/modals/ReserveModal.vue")['default']
    'LazyNavigationHeader': typeof import("../layers/reservation/components/navigation/NavigationHeader.vue")['default']
    'LazyNavigationSubMenu': typeof import("../layers/reservation/components/navigation/SubMenu.vue")['default']
    'LazyReservationCard': typeof import("../layers/reservation/components/reservation/ReservationCard.vue")['default']
    'LazyReservationForm': typeof import("../layers/reservation/components/reservation/ReservationForm.vue")['default']
    'LazyReservationList': typeof import("../layers/reservation/components/reservation/ReservationList.vue")['default']
    'LazyTeamCard': typeof import("../layers/reservation/components/team/TeamCard.vue")['default']
    'LazyTeamCardList': typeof import("../layers/reservation/components/team/TeamCardList.vue")['default']
    'LazyTeamCardPreview': typeof import("../layers/reservation/components/team/TeamCardPreview.vue")['default']
    'LazyTeamCards': typeof import("../layers/reservation/components/team/TeamCards.vue")['default']
    'LazyTeamProfile': typeof import("../layers/reservation/components/team/TeamProfile.vue")['default']
    'LazyTeamProfileEdit': typeof import("../layers/reservation/components/team/TeamProfileEdit.vue")['default']
    'LazyUserAnimals': typeof import("../layers/reservation/components/user/UserAnimals.vue")['default']
    'LazyUserDetail': typeof import("../layers/reservation/components/user/UserDetail.vue")['default']
    'LazyUserForm': typeof import("../layers/reservation/components/user/UserForm.vue")['default']
    'LazyUAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'LazyUAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'LazyUAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'LazyUAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'LazyUBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'LazyUButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'LazyUButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'LazyUCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'LazyUChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'LazyUDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'LazyUIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'LazyUKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'LazyULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'LazyUMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'LazyUMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'LazyUProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'LazyUCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'LazyUForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'LazyUFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'LazyUInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'LazyUInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'LazyURadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'LazyURadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'LazyURange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'LazyUSelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'LazyUSelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'LazyUTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'LazyUToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'LazyUTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'LazyUCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'LazyUContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'LazyUDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'LazyUSkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'LazyUBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'LazyUCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'LazyUCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'LazyUHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'LazyUPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'LazyUTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'LazyUVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'LazyUContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'LazyUModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'LazyUModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'LazyUNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'LazyUNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'LazyUPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'LazyUSlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'LazyUSlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'LazyUTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyUModals': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyUSlideovers': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const ActiviteeDetail: typeof import("../layers/reservation/components/ActiviteeDetail.vue")['default']
export const ActiviteeDetailItem: typeof import("../layers/reservation/components/ActiviteeDetailItem.vue")['default']
export const ActivityCard: typeof import("../layers/reservation/components/ActivityCard.vue")['default']
export const DogCard: typeof import("../layers/reservation/components/DogCard.vue")['default']
export const DogCardList: typeof import("../layers/reservation/components/DogCardList.vue")['default']
export const HelloWorld: typeof import("../layers/reservation/components/HelloWorld.vue")['default']
export const IsApproved: typeof import("../layers/reservation/components/IsApproved.vue")['default']
export const LoginButton: typeof import("../layers/reservation/components/LoginButton.vue")['default']
export const LoginControls: typeof import("../layers/reservation/components/LoginControls.vue")['default']
export const MomentAgo: typeof import("../layers/reservation/components/MomentAgo.vue")['default']
export const MyFooter: typeof import("../layers/reservation/components/MyFooter.vue")['default']
export const TheWelcome: typeof import("../layers/reservation/components/TheWelcome.vue")['default']
export const WelcomeItem: typeof import("../layers/reservation/components/WelcomeItem.vue")['default']
export const AnimalCard: typeof import("../layers/reservation/components/animal/AnimalCard.vue")['default']
export const AnimalForm: typeof import("../layers/reservation/components/animal/AnimalForm.vue")['default']
export const AnimalList: typeof import("../layers/reservation/components/animal/AnimalList.vue")['default']
export const AnimalSelect: typeof import("../layers/reservation/components/animal/AnimalSelect.vue")['default']
export const ButtonsCardAddButton: typeof import("../layers/reservation/components/buttons/CardAddButton.vue")['default']
export const ButtonsFacebookButton: typeof import("../layers/reservation/components/buttons/FacebookButton.vue")['default']
export const CalendarAdminCalendar: typeof import("../layers/reservation/components/calendar/AdminCalendar.vue")['default']
export const CalendarAvailabilitiesCalendar: typeof import("../layers/reservation/components/calendar/AvailabilitiesCalendar.vue")['default']
export const CalendarClientCalendar: typeof import("../layers/reservation/components/calendar/ClientCalendar.vue")['default']
export const ColorpickerColorCircle: typeof import("../layers/reservation/components/colorpicker/ColorCircle.vue")['default']
export const ColorpickerColorPicker: typeof import("../layers/reservation/components/colorpicker/ColorPicker.vue")['default']
export const EventUtils: typeof import("../layers/reservation/components/event-utils")['default']
export const IconsIconCommunity: typeof import("../layers/reservation/components/icons/IconCommunity.vue")['default']
export const IconsIconDocumentation: typeof import("../layers/reservation/components/icons/IconDocumentation.vue")['default']
export const IconsIconEcosystem: typeof import("../layers/reservation/components/icons/IconEcosystem.vue")['default']
export const IconsIconHamburger: typeof import("../layers/reservation/components/icons/IconHamburger.vue")['default']
export const IconsIconSupport: typeof import("../layers/reservation/components/icons/IconSupport.vue")['default']
export const IconsIconTooling: typeof import("../layers/reservation/components/icons/IconTooling.vue")['default']
export const IconsIconUser: typeof import("../layers/reservation/components/icons/IconUser.vue")['default']
export const InputsImageFileDisplay: typeof import("../layers/reservation/components/inputs/ImageFileDisplay.vue")['default']
export const InputsImageFileInput: typeof import("../layers/reservation/components/inputs/ImageFileInput.vue")['default']
export const ModalsModal: typeof import("../layers/reservation/components/modals/Modal.vue")['default']
export const ModalsReserveModal: typeof import("../layers/reservation/components/modals/ReserveModal.vue")['default']
export const NavigationHeader: typeof import("../layers/reservation/components/navigation/NavigationHeader.vue")['default']
export const NavigationSubMenu: typeof import("../layers/reservation/components/navigation/SubMenu.vue")['default']
export const ReservationCard: typeof import("../layers/reservation/components/reservation/ReservationCard.vue")['default']
export const ReservationForm: typeof import("../layers/reservation/components/reservation/ReservationForm.vue")['default']
export const ReservationList: typeof import("../layers/reservation/components/reservation/ReservationList.vue")['default']
export const TeamCard: typeof import("../layers/reservation/components/team/TeamCard.vue")['default']
export const TeamCardList: typeof import("../layers/reservation/components/team/TeamCardList.vue")['default']
export const TeamCardPreview: typeof import("../layers/reservation/components/team/TeamCardPreview.vue")['default']
export const TeamCards: typeof import("../layers/reservation/components/team/TeamCards.vue")['default']
export const TeamProfile: typeof import("../layers/reservation/components/team/TeamProfile.vue")['default']
export const TeamProfileEdit: typeof import("../layers/reservation/components/team/TeamProfileEdit.vue")['default']
export const UserAnimals: typeof import("../layers/reservation/components/user/UserAnimals.vue")['default']
export const UserDetail: typeof import("../layers/reservation/components/user/UserDetail.vue")['default']
export const UserForm: typeof import("../layers/reservation/components/user/UserForm.vue")['default']
export const UAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const UAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const UAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const UAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const UBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const UButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const UButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const UCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const UChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const UDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const UIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const UKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const ULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const UMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const UMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const UProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const UCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const UForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const UFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const UInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const UInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const URadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const URadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const URange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const USelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const USelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const UTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const UToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const UTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const UCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const UContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const UDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const USkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const UBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const UCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const UCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const UHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const UPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const UTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const UVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const UContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const UModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const UModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const UNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const UNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const UPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const USlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const USlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const UTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const UModals: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const USlideovers: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyActiviteeDetail: typeof import("../layers/reservation/components/ActiviteeDetail.vue")['default']
export const LazyActiviteeDetailItem: typeof import("../layers/reservation/components/ActiviteeDetailItem.vue")['default']
export const LazyActivityCard: typeof import("../layers/reservation/components/ActivityCard.vue")['default']
export const LazyDogCard: typeof import("../layers/reservation/components/DogCard.vue")['default']
export const LazyDogCardList: typeof import("../layers/reservation/components/DogCardList.vue")['default']
export const LazyHelloWorld: typeof import("../layers/reservation/components/HelloWorld.vue")['default']
export const LazyIsApproved: typeof import("../layers/reservation/components/IsApproved.vue")['default']
export const LazyLoginButton: typeof import("../layers/reservation/components/LoginButton.vue")['default']
export const LazyLoginControls: typeof import("../layers/reservation/components/LoginControls.vue")['default']
export const LazyMomentAgo: typeof import("../layers/reservation/components/MomentAgo.vue")['default']
export const LazyMyFooter: typeof import("../layers/reservation/components/MyFooter.vue")['default']
export const LazyTheWelcome: typeof import("../layers/reservation/components/TheWelcome.vue")['default']
export const LazyWelcomeItem: typeof import("../layers/reservation/components/WelcomeItem.vue")['default']
export const LazyAnimalCard: typeof import("../layers/reservation/components/animal/AnimalCard.vue")['default']
export const LazyAnimalForm: typeof import("../layers/reservation/components/animal/AnimalForm.vue")['default']
export const LazyAnimalList: typeof import("../layers/reservation/components/animal/AnimalList.vue")['default']
export const LazyAnimalSelect: typeof import("../layers/reservation/components/animal/AnimalSelect.vue")['default']
export const LazyButtonsCardAddButton: typeof import("../layers/reservation/components/buttons/CardAddButton.vue")['default']
export const LazyButtonsFacebookButton: typeof import("../layers/reservation/components/buttons/FacebookButton.vue")['default']
export const LazyCalendarAdminCalendar: typeof import("../layers/reservation/components/calendar/AdminCalendar.vue")['default']
export const LazyCalendarAvailabilitiesCalendar: typeof import("../layers/reservation/components/calendar/AvailabilitiesCalendar.vue")['default']
export const LazyCalendarClientCalendar: typeof import("../layers/reservation/components/calendar/ClientCalendar.vue")['default']
export const LazyColorpickerColorCircle: typeof import("../layers/reservation/components/colorpicker/ColorCircle.vue")['default']
export const LazyColorpickerColorPicker: typeof import("../layers/reservation/components/colorpicker/ColorPicker.vue")['default']
export const LazyEventUtils: typeof import("../layers/reservation/components/event-utils")['default']
export const LazyIconsIconCommunity: typeof import("../layers/reservation/components/icons/IconCommunity.vue")['default']
export const LazyIconsIconDocumentation: typeof import("../layers/reservation/components/icons/IconDocumentation.vue")['default']
export const LazyIconsIconEcosystem: typeof import("../layers/reservation/components/icons/IconEcosystem.vue")['default']
export const LazyIconsIconHamburger: typeof import("../layers/reservation/components/icons/IconHamburger.vue")['default']
export const LazyIconsIconSupport: typeof import("../layers/reservation/components/icons/IconSupport.vue")['default']
export const LazyIconsIconTooling: typeof import("../layers/reservation/components/icons/IconTooling.vue")['default']
export const LazyIconsIconUser: typeof import("../layers/reservation/components/icons/IconUser.vue")['default']
export const LazyInputsImageFileDisplay: typeof import("../layers/reservation/components/inputs/ImageFileDisplay.vue")['default']
export const LazyInputsImageFileInput: typeof import("../layers/reservation/components/inputs/ImageFileInput.vue")['default']
export const LazyModalsModal: typeof import("../layers/reservation/components/modals/Modal.vue")['default']
export const LazyModalsReserveModal: typeof import("../layers/reservation/components/modals/ReserveModal.vue")['default']
export const LazyNavigationHeader: typeof import("../layers/reservation/components/navigation/NavigationHeader.vue")['default']
export const LazyNavigationSubMenu: typeof import("../layers/reservation/components/navigation/SubMenu.vue")['default']
export const LazyReservationCard: typeof import("../layers/reservation/components/reservation/ReservationCard.vue")['default']
export const LazyReservationForm: typeof import("../layers/reservation/components/reservation/ReservationForm.vue")['default']
export const LazyReservationList: typeof import("../layers/reservation/components/reservation/ReservationList.vue")['default']
export const LazyTeamCard: typeof import("../layers/reservation/components/team/TeamCard.vue")['default']
export const LazyTeamCardList: typeof import("../layers/reservation/components/team/TeamCardList.vue")['default']
export const LazyTeamCardPreview: typeof import("../layers/reservation/components/team/TeamCardPreview.vue")['default']
export const LazyTeamCards: typeof import("../layers/reservation/components/team/TeamCards.vue")['default']
export const LazyTeamProfile: typeof import("../layers/reservation/components/team/TeamProfile.vue")['default']
export const LazyTeamProfileEdit: typeof import("../layers/reservation/components/team/TeamProfileEdit.vue")['default']
export const LazyUserAnimals: typeof import("../layers/reservation/components/user/UserAnimals.vue")['default']
export const LazyUserDetail: typeof import("../layers/reservation/components/user/UserDetail.vue")['default']
export const LazyUserForm: typeof import("../layers/reservation/components/user/UserForm.vue")['default']
export const LazyUAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const LazyUAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const LazyUAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const LazyUAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const LazyUBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const LazyUButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const LazyUButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const LazyUCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const LazyUChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const LazyUDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const LazyUIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const LazyUKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const LazyULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const LazyUMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const LazyUMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const LazyUProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const LazyUCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const LazyUForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const LazyUFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const LazyUInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const LazyUInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const LazyURadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const LazyURadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const LazyURange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const LazyUSelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const LazyUSelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const LazyUTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const LazyUToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const LazyUTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const LazyUCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const LazyUContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const LazyUDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const LazyUSkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const LazyUBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const LazyUCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const LazyUCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const LazyUHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const LazyUPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const LazyUTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const LazyUVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const LazyUContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const LazyUModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const LazyUModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const LazyUNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const LazyUNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const LazyUPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const LazyUSlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const LazyUSlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const LazyUTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyUModals: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyUSlideovers: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
